import javax.swing.JOptionPane;

import java.text.DecimalFormat;
import java.text.NumberFormat;

public class cConvert extends javax.swing.JFrame{
	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public cConvert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
          
    private void initComponents() {

    	fCurrency = new javax.swing.ButtonGroup();
        sCurrency = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fUSD = new javax.swing.JRadioButton();
        fEUR = new javax.swing.JRadioButton();
        fPLN = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sUSD = new javax.swing.JRadioButton();
        sEUR = new javax.swing.JRadioButton();
        sPLN = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        kwota = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        gWynik = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        wynik = new javax.swing.JTextField();

        fCurrency.add(fUSD);
        fCurrency.add(fEUR);
        fCurrency.add(fPLN);

        sCurrency.add(sUSD);
        sCurrency.add(sEUR);
        sCurrency.add(sPLN);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Witaj w wirtualnym kantorze!");

        jLabel2.setText("Wybierz walutê, któr¹ chcesz wymieniæ:");

        fUSD.setText("USD");

        fEUR.setText("EUR");

        fPLN.setText("PLN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fUSD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fEUR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fPLN))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fUSD)
                    .addComponent(fEUR)
                    .addComponent(fPLN))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel3.setText("Wybierz walutê, na któr¹ chcesz wymieniæ:");

        sUSD.setText("USD");

        sEUR.setText("EUR");

        sPLN.setText("PLN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(sUSD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sEUR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sPLN)
                .addGap(0, 43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sUSD)
                    .addComponent(sEUR)
                    .addComponent(sPLN))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLabel4.setText("Podaj kwotê:");

        kwota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kwotaKeyTyped(evt);
            }
        });

        reset.setText("Resetuj");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        exit.setText("WyjdŸ");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        gWynik.setText("Wymieñ");
        gWynik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gWynikActionPerformed(evt);
            }
        });

        jLabel5.setText("Wymieniona kwota:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(wynik, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(kwota, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(gWynik))))
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exit)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kwota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gWynik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wynik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(reset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {                                     
        System.exit(0);
    }                                    

    private void gWynikActionPerformed(java.awt.event.ActionEvent evt) {                                       
       
        
        Double kursUSD = 3.62;
        Double kursEUR = 4.24;
        Double kursEURtoUSD = 1.16;
        Double cAmount = 0.00;
        cAmount = Double.parseDouble(kwota.getText());
        
        NumberFormat formatter = new DecimalFormat("#0.00");
        
        if(fUSD.isSelected() && sPLN.isSelected()){
            Double sum = cAmount * kursUSD;
            String sum2 = formatter.format(sum);
            String sum3 = String.valueOf(sum2);
            wynik.setText(sum3);
            
        }
        else if(fPLN.isSelected() && sUSD.isSelected()){
            Double sum = cAmount / kursUSD;
            String sum2 = formatter.format(sum);
            String sum3 = String.valueOf(sum2);
            wynik.setText(sum3);
        }
        else if(fPLN.isSelected() && sEUR.isSelected()){
            Double sum = cAmount / kursEUR;
            String sum2 = formatter.format(sum);
            String sum3 = String.valueOf(sum2);
            wynik.setText(sum3);
        }
        else if(fEUR.isSelected() && sPLN.isSelected()){
            Double sum = cAmount * kursEUR;
            String sum2 = formatter.format(sum);
            String sum3 = String.valueOf(sum2);
            wynik.setText(sum3);
        }
        else if(fEUR.isSelected() && sUSD.isSelected()){
            Double sum = cAmount * kursEURtoUSD;
            String sum2 = formatter.format(sum);
            String sum3 = String.valueOf(sum2);
            wynik.setText(sum3);
        }
        else if(fUSD.isSelected() && sEUR.isSelected()){
            Double sum = cAmount / kursEURtoUSD;
            String sum2 = formatter.format(sum);
            String sum3 = String.valueOf(sum2);
            wynik.setText(sum3);
        }
        else if(fUSD.isSelected() && sUSD.isSelected()){
            JOptionPane.showMessageDialog(rootPane,
                "Ta sama waluta");
        }
        else if(fPLN.isSelected() && sPLN.isSelected()){
            JOptionPane.showMessageDialog(rootPane,
                "Ta sama waluta");
        }
        else if(fEUR.isSelected() && sEUR.isSelected()){
            JOptionPane.showMessageDialog(rootPane,
                "Ta sama waluta");
        }
    }                                      

    private void kwotaKeyTyped(java.awt.event.KeyEvent evt) {                               
        if(!isNumber(evt.getKeyChar()))
            evt.consume();
    }                              

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {                                      
        kwota.setText(" ");
        wynik.setText(" ");
    }                                     

    
    private boolean isNumber(char zn){
        
       return zn >= '0' && zn <= '9';
    }
    /**
     * @param args the command line arguments
     */

	public static void main(String[] args) {
		try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cConvert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton exit;
    private javax.swing.ButtonGroup fCurrency;
    private javax.swing.JRadioButton fEUR;
    private javax.swing.JRadioButton fPLN;
    private javax.swing.JRadioButton fUSD;
    private javax.swing.JButton gWynik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kwota;
    private javax.swing.JButton reset;
    private javax.swing.ButtonGroup sCurrency;
    private javax.swing.JRadioButton sEUR;
    private javax.swing.JRadioButton sPLN;
    private javax.swing.JRadioButton sUSD;
    private javax.swing.JTextField wynik;
    // End of variables declaration          

	}


